# @format

debug: false
dev: false
version: 0.0.1
isSetup: false
port: 3001
cookies:
  signed: true
  httpOnly: false
  maxAge: -1
logs:
  newLogFileFrequency: 24h
  maxFileSize: 50m
accounts:
  supportedTypes:
    custom: true
    google: false
    microsoft: false
database:
  url: localhost
  port: '27017'
  name: schoolable
passwords:
  length:
    min: 5
    max: 20
language: SWE
smtpOptions:
  host: gmail
  port: 587
  secure: true
  username: username
  password: password
allowedFileTypes:
  - ext: '.doc'
    mimeType: 'application/msword'
  - ext: '.docx'
    mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  - ext: '.gif'
    mimeType: 'image/gif'
  - ext: '.jpg'
    mimeType: 'image/jpeg'
  - ext: '.jpeg'
    mimeType: 'image/jpeg'
  - ext: '.mp3'
    mimeType: 'audio/mpeg'
  - ext: '.mp4'
    mimeType: 'video/mp4'
  - ext: '.mpeg'
    mimeType: 'video/mpeg'
  - ext: '.odp'
    mimeType: 'application/vnd.oasis.opendocument.presentation'
  - ext: '.ods'
    mimeType: 'application/vnd.oasis.opendocument.spreadsheet'
  - ext: '.odt'
    mimeType: 'application/vnd.oasis.opendocument.text'
  - ext: '.png'
    mimeType: 'image/png'
  - ext: '.pdf	'
    mimeType: 'application/pdf'
  - ext: '.ppt'
    mimeType: 'application/vnd.ms-powerpoint'
  - ext: '.pptx'
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
  - ext: '.txt'
    mimeType: 'text/plain'
  - ext: '.wav'
    mimeType: 'audio/wav'
  - ext: '.xls'
    mimeType: 'application/vnd.ms-excel'
  - ext: '.xlsx'
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  - ext: '.zip'
    mimeType: 'application/zip'
