apiVersion: skaffold/v2beta21
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: schoolable-platform
  artifacts:
    - image: eu.gcr.io/schoolable-platform/client
      context: client
      kaniko:
        dockerfile: Dockerfile.dev
        cache: {}
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.sass"
            dest: .
    - image: eu.gcr.io/schoolable-platform/auth
      context: auth
      kaniko:
        dockerfile: Dockerfile.dev
        cache: {}
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.yml"
            dest: .
    - image: eu.gcr.io/schoolable-platform/courses
      context: courses
      kaniko:
        dockerfile: Dockerfile.dev
        cache: {}
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.yml"
            dest: .
    - image: eu.gcr.io/schoolable-platform/remove-queue
      context: removeQueue
      kaniko:
        dockerfile: Dockerfile.dev
        cache: {}
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.yml"
            dest: .
    - image: eu.gcr.io/schoolable-platform/phases
      context: phases
      kaniko:
        dockerfile: Dockerfile.dev
        cache: {}
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.sass"
            dest: .
