apiVersion: skaffold/v2beta21
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: schoolable-platform
    kanikoImage: gcr.io/kaniko-project/executor:v1.6.0
  artifacts:
    - image: eu.gcr.io/schoolable-platform/client
      context: client
      kaniko:
        timeout: "60m"
        dockerfile: Dockerfile.dev
        cache: {}
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.sass"
            dest: .
          - src: "**/*.module.sass"
            dest: .
    - image: eu.gcr.io/schoolable-platform/auth
      context: auth
      kaniko:
        dockerfile: Dockerfile.dev
        cache: {}
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.yml"
            dest: .
    - image: eu.gcr.io/schoolable-platform/courses
      context: courses
      kaniko:
        dockerfile: Dockerfile.dev
        cache: {}
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.yml"
            dest: .
    - image: eu.gcr.io/schoolable-platform/remove-queue
      context: removeQueue
      kaniko:
        dockerfile: Dockerfile.dev
        cache: {}
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.yml"
            dest: .
    - image: eu.gcr.io/schoolable-platform/phases
      context: phases
      kaniko:
        dockerfile: Dockerfile.dev
        cache: {}
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.yml"
            dest: .
    - image: eu.gcr.io/schoolable-platform/phase-items
      context: phaseItems
      kaniko:
        dockerfile: Dockerfile.dev
        cache: {}
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.yml"
            dest: .
    - image: eu.gcr.io/schoolable-platform/submissions
      context: submissions
      kaniko:
        dockerfile: Dockerfile.dev
        cache: {}
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.yml"
            dest: .
    - image: eu.gcr.io/schoolable-platform/calendar
      context: calendar
      kaniko:
        dockerfile: Dockerfile.dev
        cache: {}
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.yml"
            dest: .
    - image: eu.gcr.io/schoolable-platform/session
      context: session
      kaniko:
        dockerfile: Dockerfile.dev
        cache: {}
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.yml"
            dest: .
