# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: session-redis-depl
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: session-redis
#   template:
#     metadata:
#       labels:
#         app: session-redis
#     spec:
#       containers:
#         - name: session-redis
#           image: redis
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: session-redis-srv
# spec:
#   selector:
#     app: session-redis
#   ports:
#     - name: db
#       protocol: TCP
#       port: 6379
#       targetPort: 6379
